language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t chansd5/react-nginx-docker-templater -f Dockerfile.dev .

script:
  - docker run -e CI=true chansd5/docker-react npm run test